name: CI

on:
  pull_request:

jobs:
  code_style_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install dependencies
        run: npm ci

      - name: Fix ESLint Issues
        uses: sibiraj-s/action-eslint@v2
        continue-on-error: true
        with:
          eslint-args: '--fix'
          extensions: 'js,ts,tsx,html'
          annotations: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ESLint Fixes
          skip_fetch: true